

[hosts]

  [[hosts.dc1.dev]]
  ip = "10.0.0.1"
  name = "db"

  [[hosts.dc1.dev]]
  ip = "10.0.0.2"
  name = "nginx"

  [[hosts.dc1.prod]]
  ip = "10.1.0.1"
  name = "db"

  [[hosts.dc1.prod]]
  ip = "10.1.0.2"
  name = "nginx"
